matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew update
        - brew install rocksdb
      script:
        - script/test
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew update
        - brew install swiftlint
      script:
        - swiftlint
    - os: linux
      dist: trusty
      sudo: false
      services: docker
      before_install:
        - docker pull jatoben/swiftrocks:latest
      script:
        - docker run -v "$(pwd):/src" jatoben/swiftrocks:latest /src/script/test

